---
- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_path }}"
    remote_src: yes

- name: Set up wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_path }}/wp-config.php"

- name: Set permissions for WordPress
  file:
    path: "{{ wordpress_path }}"
    owner: www-data
    group: www-data
    recurse: yes
